# If you are using mssql, derby, hsqldb, h2 or oracle with one of the
# ActiveRecord JDBC adapters, configure your database setting as the
# example below. (Note that for oracle you will need to include the
# driver jar on the classpath.):
#
#development:
#  adapter: mssql
#  username: <username>
#  password: <password>
#  host: localhost
#  database: dummy

# If you are using db2, sybase, informix or prefer to directly specify
# the JDBC connection information, configure your database setting as
# the example below (requires you to download and manually install the
# database vendor's JDBC driver .jar file). See your driver
# documentation for the apropriate driver class and connection string:
#
#development:
#  adapter: jdbc
#  username: <username>
#  password: <password>
#  driver: com.ibm.db2.jcc.DB2Driver
#  url: jdbc:db2://localhost:5021/dummy

defaults: &defaults
  adapter: sqlite

development:
  database: db/development.sqlite3
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  database: db/test.sqlite3
  <<: *defaults
production:
  uri: DataMapper.setup( :default, ENV[ 'DATABASE_URL' ] )
